# Generated by Django 4.1.2 on 2023-04-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='hour',
            field=models.IntegerField(choices=[(1, '12:30 - 13:20'), (2, '13:30 - 14:20'), (3, '14:30 - 15:20'), (4, '15:30 - 16:20'), (5, '16:30 - 17:20'), (6, '17:30 - 18:20'), (7, '18:30 - 19:20')], default=2, verbose_name='HoursChoices'),
            preserve_default=False,
        ),
    ]
