# Generated by Django 4.1.2 on 2023-04-18 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_grades'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grades',
            new_name='Grade',
        ),
    ]
