# Generated by Django 4.1.5 on 2023-04-19 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_grades_grade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('day', 'hour', 'class_id')},
        ),
    ]
