# Generated by Django 4.1.5 on 2023-04-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_timetable_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='year',
            field=models.IntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V'), (6, 'VI'), (7, 'VII'), (8, 'VIII'), (9, 'IX'), (10, 'X'), (11, 'XI'), (12, 'XII')], default=1, verbose_name='YearChoices'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mail',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='hour',
            field=models.IntegerField(choices=[(1, '07:30 - 08:20'), (2, '08:30 - 09:20'), (3, '09:30 - 10:20'), (4, '10:30 - 11:20'), (5, '11:30 - 12:20'), (6, '12:30 - 13:20'), (7, '13:30 - 14:20'), (8, '14:30 - 15:20'), (9, '15:30 - 16:20'), (10, '16:30 - 17:20'), (11, '17:30 - 18:20'), (12, '18:30 - 19:20')], verbose_name='HoursChoices'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('year', 'letter'), name='unique_classroom_name'),
        ),
    ]
