# Generated by Django 4.1.5 on 2023-04-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_class_classroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='year',
            field=models.IntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V'), (6, 'VI'), (7, 'VII'), (8, 'VIII'), (9, 'IX'), (10, 'X'), (11, 'XI'), (12, 'XII')], default=1, verbose_name='Study Year'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.IntegerField(choices=[(1, 'Luni'), (2, 'Marti'), (3, 'Miercuri'), (4, 'Joi'), (5, 'Vineri')], verbose_name='Day'),
        ),
    ]
