# Generated by Django 4.1.5 on 2023-04-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_classroom_year_alter_timetable_day'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassAsignment',
            new_name='ClassAssignment',
        ),
    ]
